### ISSUE TITLE
--no-save should be the default

### ISSUE THREAD

**Issue by kutzi** [joeferner/redis-commander#167]
In my experience the default save behaviour causes more issues than it solves.
E.g.
- opening connections, I don't want to connect to, currently.
- accidentally doing actions on the connection, I didn't want to
- worst of all: it saves the password in clear text in your homedirectory

**Comment by cduchesne** [comment]
I completely agree with this. I'm frequently deleting my config.

**Comment by cyxou** [comment]
+1

**Comment by sseide** [comment]
With latest version it is possible to create your own config to disable connection saving as default setting. Otherwise the cli flag `--nosave` is available to disable this feature at your will.

Will not change default behaviour as other people expect it to work that way (some say so some say so)

For saving passwords - its possible to restrict file access to these for no one else to read it. There could be done some password obfuscation, but password needs to be decrypted on startup to be able to connect to redis servers... Hashing passwords does not work due to it.

But feel free to make some suggestions or provide a PR to let redis commander connect to redis servers without saving password in config file (e.g. ask first user connection to ui for password or similiar).
