### ISSUE TITLE
Unable to get  local issuer certificate

### ISSUE THREAD

**Issue by ae6rt** [joeferner/redis-commander#366]
# Platform

```
Darwin hostname 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```
# Version

```
redis-commander@0.6.6
```

# Expected behavior

* redis-commander would offer a command option to point to a CA bundle to support connections to Redis over TLS
* or, honor trusted certificates in OS/X Keychain 

# Actual behavior

```
$ redis-commander  --redis-port 6380 --redis-password sekrit  --redis-tls
Using scan instead of keys
No Save: false
listening on 0.0.0.0:8081
access with browser at http://127.0.0.1:8081
setUpConnection (R:localhost:26380:0) Redis error Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
```

The Redis instance lies behind a Layer 4 proxy terminating TLS.  The proxy returns a certificate chain that, with root certificates in OS/X Keychain, is complete.

**Comment by sseide** [comment]
dont know about MacOS specifica but its using default nodejs for certificate handling - you have to check with nodejs docs to find out where certificates needs to go.

And setting special tls configurations like custom root certs is already part of redis commander - as written in the docs you need to add your connection to the configuration file (no command line posssible) and there you can set all params needed to setup tls config at the connections tls parameter as an object instead of boolean value.

https://github.com/joeferner/redis-commander/blob/master/docs/connections.md#connection-parameters parameter name `tls`

**Comment by ae6rt** [comment]
Thank you.  I found a way to make it work

```
NODE_EXTRA_CA_CERTS=/Users/me/lib/easycert-ca/xoom-qa-hsm.pem  redis-commander  --redis-port 26380 --redis-password sekrit  --redis-tls
```
