### ISSUE TITLE
Default view mode

### ISSUE THREAD

**Issue by ridvansumset** [joeferner/redis-commander#375]
If data is a valid JSON, it would be nice to view it in tree mode by default. Otherwise, we always have to click  "view mode tree" button.

**Comment by ValeSauer** [comment]
+1 if the JSON view becomes more performant. The JSON view breaks chrome with very large payloads.

**Comment by sseide** [comment]
@ValeSauer regarding performance - you are right as currently used lib `json-tree` (https://github.com/lmenezes/json-tree) is not the most performant one. Do you know another lib that can be used as a replacement? It must protect against XSS vulnerabilities.

JsonTreeViewer (https://github.com/summerstyle/jsonTreeViewer/issues/13) for example does not...

**Comment by sseide** [comment]
ok, switched json viewer to another library which seems to be a bit more performant. 
@ValeSauer can you check with your data please

And added config value and env var to allow using this json display mode as defautl. Old default (display as text) is not changed, you need to enable it explicitly.

Either set `ui.jsonViewAsDefault = "all"` in your local config file or set env var `"VIEW_JSON_DEFAULT=all"`

If you like this new behaviour for strings only and not for other types you can set this config to `"string"` instead of `"all"`. As Json view mode is only supported for string and hash by now (will add more in the future) setting this config to `"string,hash"` works to but is now equivalent to `"all"`.
As written in docs/configuration.md this config value accepts a list of datatypes to display as json to not force all of them as json per default...

**Comment by sseide** [comment]
@ridvansumset - does it help you? does it work?
@ValeSauer - better now? 

Can ticket be closed now?

**Comment by ValeSauer** [comment]
Yes, much better now.

**Comment by sseide** [comment]
new version 0.6.7 with fix available on npm too
