### ISSUE TITLE
redis-commander cannot connect to password-protected redis when running in Kubernetes

### ISSUE THREAD

**Issue by omichels** [joeferner/redis-commander#397]
we ran into a complicated issue when trying to deploy redis and redis-commander in Kubernetes. 
redis-commander was not able to connect onto a password protected redis db, even after correctly setting REDIS_HOST, REDIS_PORT, REDIS_PASSWORD in yaml deployment.

We did some debugging into the running container and observed that setting "REDIS_HOST=redis" resulted in " --redis-port tcp://10.0.24.23:6379" on the command line.
We gave up due to our project timeboxing and changed "args" in the K8S deployment:
...
        image: elkcommoncontainer.azurecr.io/redis-commander:2020-03-05
        args: ["sh", "-c", "cd /redis-commander; /usr/local/bin/node ./bin/redis-commander --redis-host redis --redis-password SECRET "]
...

To make matters worse, we were unable to reproduce the bug with docker or docker-compose on a developer box. I suspect that either the entrypoint.sh is wrong for Kubernetes or there is a bug in the node module "redis-parser" in lib/parser.js

excerpt from our logs:

Creating custom redis-commander config '/redis-commander/config/local-production.json'.
Parsing 1 REDIS_HOSTS into custom redis-commander config '/redis-commander/config/local-production.json'.
node ./bin/redis-commander --redis-port tcp://10.0.24.23:6379 --redis-password <set>
Using scan instead of keys
Found long tcp port descriptor with hostname in redis-port param, parse this as host and port value
No Save: false
listening on 0.0.0.0:8081
access with browser at http://127.0.0.1:8081
Redis Connection 10.0.24.23:6379 using Redis DB #0
setUpConnection (R:redis:6379:0) Redis error ReplyError: NOAUTH Authentication required.
    at parseError (/redis-commander/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/redis-commander/node_modules/redis-parser/lib/parser.js:302:14)
redis command "command" not supported, cannot build dynamic command list for (R:redis:6379:0
{ ReplyError: NOAUTH Authentication required.
    at parseError (/redis-commander/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/redis-commander/node_modules/redis-parser/lib/parser.js:302:14) command: { name: 'select', args: [ '0' ] } }

**Comment by sseide** [comment]
Its an Kubernetes problem, not Redis-Commander.

As you deployed an "redis" service into the same namespace its automatically providing an environment variable `REDIS_PORT` with the `tcp:/...` value.

Some time ago i added a fix for that to correctly parses this redis connection url and use this instead of throwing an exception (no valid port number) to allow to-configurations inside docker-compose and kubernetes environments. Thats where the line
```
Redis Connection 10.0.24.23:6379 using Redis DB #0
```
cames from...

To solve your problem:

a) As you use `REDIS_HOSTS` env var and not the ones to setup a single connection just add the env var `REDIS_PORT` with an empty string to your kubernetes deployment. - this connection info is ignored than

b) use this connection (as there seems to be a redis running) and provide the needed password via `REDIS_PASSWORD` or `REDIS_PASSWORD_FILE` env var.

**Comment by omichels** [comment]
face-palm :-)

yes, you are perfectly right. I was using "REDIS_HOSTS" instead of "REDIS_HOST"

**Comment by sseide** [comment]
Thanks for the updates. I'll close this. When there are other questions please open a new issue.
