### ISSUE TITLE
Trying to deploy to an online environment and SSHing in - SSH is removed because of hardening.

### ISSUE THREAD

**Issue by kdevan** [joeferner/redis-commander#534]
I'm able to deploy this to an online environment just fine but then am not able to SSH in. Removing some of the `/root` folders (`rm -rf /tmp/* /root/.??* /root/cache /var/cache/apk/*`) as well as some of the hardening (removing `sshd` but maybe some other things there too) seem to be the culprits.

I'm trying to deploy this to Fly.io along with Tailscale for security but this requires SSH access. Is there any chance this could be made available so that SSH is working? If not that's alright, thankfully since this is open source I can fork and experiment on my end.

**Comment by sseide** [comment]
Hello,

No, the SSH deamon will not be part of the default image, it just opens up to much risks for most of the users.

But in your case you do not need to fork it.
Just create a new Dockerfile for you with:
```
FROM ghcr.io/joeferner/redis-commander
RUN apk update && apk upgrade && apk add openssh-server
```
Afterwards add extra packages that you need too or run additional commands as needed.

Rebuilding this image you get all updates of current redis Commander automatically without merging stuff ...

Hope this helps

**Comment by sseide** [comment]
Just a short not without going deeper into it.:

* `/tmp` (temporary) is cleared on every reboot, there is nothing persistet / nothing to copy from
* `/etc/modprobe.d` and `/etc/modules` - a docker image does not boot its own kernel, its reusing the container host one. Nothing needed from these directories
* `/root` not needed too, in regard to SSH server there will be stored the users own ssh key (nothing in original alpine image) and authorized_keys to log into as root users are there also not available in existing image

And all binary files needed by ssh-server itself are installed due to the `apk add` command (at least '/etc/init.d' not be needed. suspect booth sbin-dirs also not, but not 100% sure here)

Best regards,
Stefan
